apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: redis
  annotations:
    argocd.argoproj.io/sync-wave: "-1" # This ensures the PVC is created first
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi


